---
title: "Analysis Report Template"
author: Cole Beck
date: '2022-05-24'
output: html_document
---

```{r setup, message = FALSE}
library(Hmisc)
```

```{r helperFunctions, echo = FALSE}
# functions
## Important function - confidence interval for means (or geoemtric means)
GMECI <- function(x, B = 5000, geo = FALSE, boot = TRUE) {
  if (boot == TRUE)
  {
  if (geo == FALSE)
  {
    k <- length(x)
    mx <- rep(0, B)
    for (b in 1:B)
    {
      samp <- sample(1:k, size = k, replace = TRUE)
      bx <- x[samp]
      mbx <- mean(bx, na.rm = TRUE)
      mx[b] <- mbx
    }
    return(c(EST = (mean(x, na.rm = TRUE)),
             CILOW = (quantile(mx, 0.025, na.rm = TRUE)),
             CIHI = (quantile(mx, 0.975, na.rm = TRUE))))
  }
  if (geo == TRUE)
  {
    k <- length(x)
    mx <- rep(0, B)
    for (b in 1:B)
    {
      samp <- sample(1:k, size = k, replace = TRUE)
      bx <- x[samp]
      mbx <- mean(log(bx), na.rm = TRUE)
      mx[b] <- mbx
    }
    return(c(EST = exp(mean(log(x), na.rm = TRUE)),
             CILOW = exp(quantile(mx, 0.025, na.rm = TRUE)),
             CIHI = exp(quantile(mx, 0.975, na.rm = TRUE))))
  }
  }
  if (boot == FALSE)
  {
    if (geo == FALSE)
    {
      k <- length(x)
      mx <- mean(x, na.rm = TRUE)
      sx <- sd(x, na.rm = TRUE)
      return(c(EST = (mx),
               CILOW = (mx - qnorm(0.975) * sx/sqrt(k)),
               CIHI = (mx + qnorm(0.975) * sx/sqrt(k))))
    }
    if (geo == TRUE)
    {
      k <- length(x)
      mx <- mean(log(x), na.rm = TRUE)
      sx <- sd(log(x), na.rm = TRUE)
      return(c(EST = exp(mx),
               CILOW = exp(mx - qnorm(0.975) * sx/sqrt(k)),
               CIHI = exp(mx + qnorm(0.975) * sx/sqrt(k))))
    }
  }
}

## Important function - plot confidence interval
pCI <- function(x, PCI, w = 0.035, lwd = 1.9, col = "deepskyblue3", pch = 20)
{
  points(x, PCI[1], pch = pch, col = col, cex = 0.8)
  segments(x, PCI[2], x, PCI[3], lwd = lwd, col = col)
  segments(x - w, PCI[2], x + w, PCI[2], lwd = lwd, col = col)
  segments(x - w, PCI[3], x + w, PCI[3], lwd = lwd, col = col)
}
```

```{r dataManip}
dat <- read.csv('sot-covid.csv')
# add a label to "mopost" variable
label(dat$mopost) <- 'months post-transplant'

# Remove subjects
dat <- dat[!(dat[,'subj'] %in% c(77,78)),]

# sot_hc = 1 for SOT, 0 for healthy
dat[,'sot_hc'] <- as.numeric(dat[,'organ'] != 0)
healthy_control <- dat[,'sot_hc'] == 0

# Sort by subject ID
dat <- dat[order(dat[,'subj']),]

# Generate data for CD4 and CD8 counts
set.seed(3)
dat[,'cd4ecd1'] <- rnorm(nrow(dat), sd = 0.5)
dat[,'cd4ecd3'] <- rnorm(nrow(dat), sd = 0.5)
dat[,'cd8ecd1'] <- rnorm(nrow(dat), sd = 0.25)
dat[,'cd8pep1'] <- rnorm(nrow(dat), sd = 0.25)
dat[,'cd8pep3'] <- rnorm(nrow(dat), sd = 0.25)

# create categorical variables with labels
dat[,'organ'] <- factor(dat[,'organ'], labels = c('healthy','kidney','liver','heart','lung'))
dat[,'sex'] <- factor(dat[,'male'], labels = c('F','M'))

# for healthy, instead of 0, set to missing
dat[healthy_control,'immuno'] <- NA
dat[healthy_control,'mopost'] <- NA
```

## Descriptive statistics

```{r desc}
html(describe(dat[,1:6]))
```

## Baseline demographic and clinical characteristics of the SOT and HC groups

```{r tab1}
html(summaryM(age + sex + immuno + organ + mopost ~ sot_hc, data = dat, continuous = 3))
```

## Histogram of ELISA response

```{r hist, echo = FALSE, fig.height = 6, fig.width = 8}
nf <- layout(matrix(1:6, nrow = 3))
par(mar = c(5, 4, 4, 2) + 0.1)
hist(dat[,'rbd1'], main = 'ELISA: RBD', xlab = 'Baseline')
par(mar = c(5, 4, 2, 2) + 0.1)
hist(dat[,'rbd2'], main = '', xlab = 'Post-Dose 1')
par(mar = c(5, 4, 2, 2) + 0.1)
hist(dat[,'rbd3'], main = '', xlab = 'Post-Dose 2')
par(mar = c(5, 4, 4, 2) + 0.1)
hist(dat[,'ecd1'], main = 'ELISA: ECD', xlab = 'Baseline')
par(mar = c(5, 4, 2, 2) + 0.1)
hist(dat[,'ecd2'], main = '', xlab = 'Post-Dose 1')
par(mar = c(5, 4, 2, 2) + 0.1)
hist(dat[,'ecd3'], main = '', xlab = 'Post-Dose 2')
```

## Humoral responses

```{r figure1, echo = FALSE, fig.width = 10}
par(mfrow = c(1,2))

#### RBD
set.seed(4)

plot(0, col = "white", frame.plot = FALSE, xlim = c(0, 1.3), xlab = "",
     ylab = "Anti-RBD IgG (EU)", ylim = c(-1, 3), xaxt = 'n', main = "ELISA: RBD")
axis(1, at = c(0.2, 0.65, 1.1), c("Baseline", "Post-Dose 1", "Post-Dose 2"))

n_hc <- sum(healthy_control == 1)
n_sot <- sum(healthy_control == 0)
points(runif(n_hc, -0.015, 0.015) + 0.15, dat[healthy_control,'rbd1'], cex = 1.1, pch = 20, col = "deepskyblue2")
points(runif(n_sot, -0.015, 0.015) + 0.25, dat[!healthy_control,'rbd1'], cex = 1.1, pch = 18, col = "red1")

pCI(0.15, GMECI(dat[healthy_control,'rbd1']), col = "royalblue4", lwd = 2.1)
pCI(0.25, GMECI(dat[!healthy_control,'rbd1']), pch = 18, col = "darkred", lwd = 2.1)

points(runif(n_hc, -0.015, 0.015) + 0.6, dat[healthy_control,'rbd2'], cex = 1.1, pch = 20, col = "deepskyblue2")
points(runif(n_sot, -0.015, 0.015) + 0.7, dat[!healthy_control,'rbd2'], cex = 1.1, pch = 18, col = "red1")

pCI(0.6, GMECI(dat[healthy_control,'rbd2']), col = "royalblue4", lwd = 2.1)
pCI(0.7, GMECI(dat[!healthy_control,'rbd2']), col = "darkred", pch = 18, lwd = 2.1)

points(runif(n_hc, -0.015, 0.015) + 1.05, dat[healthy_control,'rbd3'], cex = 1.1, pch = 20, col = "deepskyblue2")
points(runif(n_sot, -0.015, 0.015) + 1.15, dat[!healthy_control,'rbd3'], cex = 1.1, pch = 18, col = "red1")

pCI(1.05, GMECI(dat[healthy_control,'rbd3']), col = "royalblue4", lwd = 2.1)
pCI(1.15, GMECI(dat[!healthy_control,'rbd3']), col = "darkred", pch = 18, lwd = 2.1)

segments(0.05, 0, 1.25, 0, col = "gray30", lwd = 1, lty = 3)
legend(0, 3, col = c("deepskyblue2", "red1"), c("HC", "SOT"), pch = c(20, 18), cex = 1.1)

mtext(expression(bold("(A)")), side = 1, cex = 1.2, line = 4)

#### ECD
set.seed(4)

plot(0, col = "white", frame.plot = FALSE, xlim = c(0, 1.3), xlab = "",
     ylab = "Anti-RBD IgG (EU)", ylim = c(-1, 3), xaxt = 'n', main = "ELISA: ECD")
axis(1, at = c(0.2, 0.65, 1.1), c("Baseline", "Post-Dose 1", "Post-Dose 2"))

points(runif(n_hc, -0.015, 0.015) + 0.15, dat[healthy_control,'ecd1'], cex = 1.1, pch = 20, col = "deepskyblue2")
points(runif(n_sot, -0.015, 0.015) + 0.25, dat[!healthy_control,'ecd1'], cex = 1.1, pch = 18, col = "red1")

pCI(0.15, GMECI(dat[healthy_control,'ecd1']), col = "royalblue4", lwd = 2.1)
pCI(0.25, GMECI(dat[!healthy_control,'ecd1']), pch = 18, col = "darkred", lwd = 2.1)

points(runif(n_hc, -0.015, 0.015) + 0.6, dat[healthy_control,'ecd1'], cex = 1.1, pch = 20, col = "deepskyblue2")
points(runif(n_sot, -0.015, 0.015) + 0.7, dat[!healthy_control,'ecd1'], cex = 1.1, pch = 18, col = "red1")

pCI(0.6, GMECI(dat[healthy_control,'ecd2']), col = "royalblue4", lwd = 2.1)
pCI(0.7, GMECI(dat[!healthy_control,'ecd2']), col = "darkred", pch = 18, lwd = 2.1)

points(runif(n_hc, -0.015, 0.015) + 1.05, dat[healthy_control,'ecd3'], cex = 1.1, pch = 20, col = "deepskyblue2")
points(runif(n_sot, -0.015, 0.015) + 1.15, dat[!healthy_control,'ecd3'], cex = 1.1, pch = 18, col = "red1")

pCI(1.05, GMECI(dat[healthy_control,'ecd3']), col = "royalblue4", lwd = 2.1)
pCI(1.15, GMECI(dat[!healthy_control,'ecd3']), col = "darkred", pch = 18, lwd = 2.1)

segments(0.05, 0, 1.25, 0, col = "gray30", lwd = 1, lty = 3)
legend(0, 3, col = c("deepskyblue2", "red1"), c("HC", "SOT"), pch = c(20, 18), cex = 1.1)

mtext(expression(bold("(B)")), side = 1, cex = 1.2, line = 4)
```

## Cellular responses and relationship with humoral responses

```{r figure2, echo = FALSE, fig.width = 10}
par(mfrow = c(1,2))

diff_cd4ecd <- dat[, 'cd4ecd3'] - dat[, 'cd4ecd1']
diff_ecd <- dat[, 'ecd3'] - dat[, 'ecd1']
x_lim <- sign(range(diff_cd4ecd)) * ceiling(abs(range(diff_cd4ecd)) * 2) / 2
y_lim <- sign(range(diff_ecd)) * ceiling(abs(range(diff_ecd)) * 2) / 2
p_x <- diff_cd4ecd[healthy_control]
p_y <- diff_ecd[healthy_control]
plot(p_x, p_y, col = 'deepskyblue2', pch = 20, frame.plot = FALSE,
  xlab = expression(paste(Delta,"CD4+OX40+CD154+ (%)")),
  ylab = expression(paste(Delta,"ELISA anti-ECD IgG (EU)")),
  xlim = x_lim, ylim = y_lim, cex = 1.1,
  main = 'Change in CD4/antibody response', xaxt = 'n', yaxt = 'n'
)
axis(1, at = seq(x_lim[1], x_lim[2], by = 0.5))
axis(2, at = seq(y_lim[1], y_lim[2], by = 0.5))

legend(x_lim[1], y_lim[2], pch = c(20,18), cex = 0.8, col = c("deepskyblue2", "red1"), c("HC", "SOT"))

mtext(expression(bold("(A)")), side = 1, cex = 1.2, line = 4)

abline(h = 0, lwd = 1.2, lty = 3, col = "gray50")
abline(v = 0, lwd = 1.2, lty = 3, col = "gray50")

points(mean(p_x, na.rm = TRUE), mean(p_y, na.rm = TRUE), col = "darkblue", pch = 20, cex = 1.4)

p_x <- diff_cd4ecd[!healthy_control]
p_y <- diff_ecd[!healthy_control]
points(p_x, p_y, col = "red1", pch = 18)
points(mean(p_x, na.rm = TRUE), mean(p_y, na.rm = TRUE), col = "darkred", pch = 18, cex = 1.4)

diff_cd8pep <- dat[, 'cd8pep3'] - dat[, 'cd8pep1']
y_lim <- sign(range(diff_cd8pep)) * ceiling(abs(range(diff_cd8pep)) * 2) / 2
p_x <- diff_cd4ecd[healthy_control]
p_y <- diff_cd8pep[healthy_control]
plot(p_x, p_y, col = "deepskyblue2", pch = 20, frame.plot = FALSE,
     xlab = expression(paste(Delta,"CD4+OX40+CD154+ (%)")),
     ylab = expression(paste(Delta,"CD8+CD25+CD137+ (%)")),
     xlim = x_lim, ylim = y_lim, cex = 1.1,
     main = "Change in CD4/CD8 response", xaxt = 'n', yaxt = 'n'
)
axis(1, at = seq(x_lim[1], x_lim[2], by = 0.5))
axis(2, at = seq(y_lim[1], y_lim[2], by = 0.5))

legend(x_lim[1], y_lim[2], pch = c(20,18), cex = 0.8, col = c("deepskyblue2", "red1"), c("HC", "SOT"))

mtext(expression(bold("(B)")), side = 1, cex = 1.2, line = 4)

abline(h = 0, lwd = 1.2, lty = 3, col = "gray50")
abline(v = 0, lwd = 1.2, lty = 3, col = "gray50")

points(mean(p_x, na.rm = TRUE), mean(p_y, na.rm = TRUE), col = "darkblue", pch = 20, cex = 1.4)

p_x <- diff_cd4ecd[!healthy_control]
p_y <- diff_cd8pep[!healthy_control]
points(p_x, p_y, col = "red1", pch = 18)
points(mean(p_x, na.rm = TRUE), mean(p_y, na.rm = TRUE), col = "darkred", pch = 18, cex = 1.4)
```
